[local]
localhost

[mongodb]
mongodb-dev.devopsd88s.online

[catalogue]
catalogue-dev.devopsd88s.online

[redis]
redis-dev.devopsd88s.online

[user]
user-dev.devopsd88s.online

[cart]
cart-dev.devopsd88s.online

[mysql]
mysql-dev.devopsd88s.online

[shipping]
shipping-dev.devopsd88s.online

[rabbitmq]
rabbitmq-dev.devopsd88s.online

[payment]
payment-dev.devopsd88s.online

[frontend]
frontend-dev.devopsd88s.online